services:

  nginx:
    build:
      dockerfile: docker/nginx.Dockerfile
      context: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/etc/nginx/includes/php.conf:/etc/nginx/includes/php.conf
      - ./docker/nginx/etc/nginx/includes/soketi.conf:/etc/nginx/includes/soketi.conf
    environment:
      TZ: 'Europe/Moscow'
      DOMAIN_APP: '${DOMAIN_APP}'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  php:
    build:
      dockerfile: docker/php.Dockerfile
      context: .
    user: '${USER_GID}:${USER_GID}'
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/php/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/usr/local/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    environment:
      TZ: 'Europe/Moscow'
      PHP_INI_TIMEZONE: 'Europe/Moscow'

      APP_NAME: 'app'
      APP_DOMAIN: '${DOMAIN_APP}'
      APP_URL: '${HTTP_PROTOCOL}://${DOMAIN_APP}'

      DB_CONNECTION: 'pgsql'
      DB_HOST: postgres-app
      DB_PORT: '5432'
      DB_DATABASE: '${POSTGRES_DB}'
      DB_USERNAME: '${POSTGRES_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'

      MEMCACHED_HOST: memcached

      REDIS_CLIENT: 'phpredis'

      REDIS_QUEUE_HOST: redis-queue
      REDIS_QUEUE_PASSWORD: null
      REDIS_QUEUE_PORT: 6379

      SOCKET_APP_ID: 'app-id'
      SOCKET_APP_KEY: 'app-key'
      SOCKET_APP_SECRET: 'app-secret'
      SOCKET_APP_CLUSTER: 'mt1'
      SOCKET_HOST: 'soketi'
      SOCKET_SCHEME: 'http'
      SOCKET_PORT: 6001
      SOCKET_CLIENT_PORT: 443
      SOCKET_CLIENT_SCHEME: '${HTTP_PROTOCOL}'

      MAIL_MAILER: 'smtp'
      MAIL_ENCRYPTION: null
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  php-queue:
    extends:
      service: php
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  postgres-app:
    image: postgres:17.2-alpine3.20
    volumes:
      - ./data/postgresql-app/data:/var/lib/postgresql/data:rw
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  memcached:
    image: memcached:1.6-alpine3.20
    environment:
      TZ: 'Europe/Moscow'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  node:
    build:
      dockerfile: docker/node.Dockerfile
      context: .
    user: '${USER_GID}:${USER_GID}'
    volumes:
      - ./laravel:/var/www/laravel
    environment:
      TZ: 'Europe/Moscow'
      APP_URL: '${HTTP_PROTOCOL}://${DOMAIN_APP}'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  soketi:
    image: quay.io/soketi/soketi:1.6-16-alpine
    environment:
      TZ: 'Europe/Moscow'
      SOKETI_REDIS_HOST: redis-soketi
      SOKETI_DEFAULT_APP_ID: 'app-id'
      SOKETI_DEFAULT_APP_KEY: 'app-key'
      SOKETI_DEFAULT_APP_SECRET: 'app-secret'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  redis-queue:
    image: redis:7.4-alpine3.20
    volumes:
      - ./data/redis-queue/data:/root/redis
    environment:
      TZ: 'Europe/Moscow'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  redis-soketi:
    image: redis:7.4-alpine3.20
    volumes:
      - ./data/redis-soketi/data:/root/redis
    environment:
      TZ: 'Europe/Moscow'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  certbot:
    image: certbot/certbot:v3.1
    volumes:
      - ./data/certbot/data/letsencrypt:/etc/letsencrypt
      - ./data/certbot/data/certbot:/var/www/certbot
    environment:
      TZ: 'Europe/Moscow'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
